
version: "3"
services:
  redis-server:
    image: 'redis'
    restart: unless-stopped
  web_en:
    image: 'videowiki-app'
    build: .
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4000", "en"]
    

  web_hi:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4001", "hi"]


  web_es:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4002", "es"]


  web_ar:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4003", "ar"]


  web_ja:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4004", "ja"]


  web_uk:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4005", "uk"]


  web_fr:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4006", "fr"]


  web_or:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4007", "or"]


  web_te:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4008", "te"]


  web_gu:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4009", "gu"]


  web_bn:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4010", "bn"]


  web_pa:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4011", "pa"]


  web_sat:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4012", "sat"]


  web_sv:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4013", "sv"]


  web_it:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4014", "it"]


  web_kn:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4015", "kn"]


  web_ml:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4016", "ml"]


  web_ta:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4017", "ta"]


  web_eu:
    image: 'videowiki-app'
    restart: unless-stopped
    volumes:
      - ./:/home/videowiki
      - /home/hassan:/home/hassan
    depends_on:
      - redis-server
    command: ["node", "index.js", "4018", "eu"]


