version: "3"
services:
  redis-server:
    image: 'redis'
    restart: unless-stopped
    ports:
      - "6379:6379"
  rabbitmq-server:
    image: 'rabbitmq'
    restart: unless-stopped
    ports:
      - "5672:5672"
  mongo-server:
    image: mongo:4.0.10
    restart: unless-stopped
    ports:
      - "27017:27017"